### ISSUE TITLE
Remove broken PHP script in mailer.html

### ISSUE THREAD

**Issue by nevinvalsaraj** [auviitkgp/auviitkgp.github.io#13]
PHP scripts, a remnant from the days the website was hosted on a PHP server, is still found at `mailer.html`, which is used to send email from the Contact page. 

TO DO:
- Remove `mailer.html`
- Remove mailing option from Contact page. 
- Update contact information at Contact page using Team Head's contact information (redundant information?).
- Optionally : remove Contact page and update `navbar` to reflect removal.

**Comment by athityakumar** [comment]
Suggestion - Add formspree.io support , and remove the php script. 

Ping @icyflame

**Comment by icyflame** [comment]
@athityakumar This has been pending for a LONG LONG time, anything you can do to solve it immediately will be much appreciated.

**Comment by athityakumar** [comment]
@icyflame - Issue seems to be fixed now with formspree. Can we close this issue? :smile:

**Comment by icyflame** [comment]
@athityakumar Yeah. Good work :+1:
