### ISSUE TITLE
Create and implement a blog using Jekyll

### ISSUE THREAD

**Issue by icyflame** [auviitkgp/auviitkgp.github.io#9]
- Choose a theme from [here](https://github.com/jekyll/jekyll/wiki/Themes).
- Implement the theme by creating a new repository `auviitkgp/blog`

**Comment by routeaccess** [comment]
The blog can be integrated into the current site by converting this repo into a jekyll-powered website repo and extending upon this. Are you suggesting that we have a separate repo for blog alone?

**Comment by icyflame** [comment]
Yes. A separate repo is the easiest way to get started. 

Changing this whole website into a Jekyll repository will take time. And it's pretty unnecessary. Our present configuration, for the website, is good enough. 

If we have a separate repo for blog, we can access it through http://auviitkgp.github.io/blog. And it would make perfect sense. 

And the setup would be very simple once we decide on the theme. That's why I suggested a separate repo.

**Comment by icyflame** [comment]
@routeaccess 
Please review and suggest a forward path.

**Comment by icyflame** [comment]
Solved by creating: http://github.com/auviitkgp/blog/

URL: http://auv-iitkgp.in/blog/
